export const R   = '#cb1c6b'
export const T   = '#00C2CB'
export const BLK = '#201b51'
export const GRY = '#faf9f6'
export const GRN = '#16a34a'
export const AMB = '#D97706'
export const W   = '#ffffff'
export const FH  = "'Bebas Neue','Arial Narrow',sans-serif"
export const FB  = "'DM Sans',-apple-system,sans-serif"
