export const R   = '#E6007E'
export const T   = '#00C2CB'
export const BLK = '#1A1A1A'
export const GRY = '#F7F5F2'
export const GRN = '#16a34a'
export const AMB = '#D97706'
export const W   = '#ffffff'
export const FH  = "'Instrument Serif',Georgia,serif"
export const FB  = "'DM Sans',-apple-system,sans-serif"
