-- ============================================================
-- KotoIQ Plans — enterprise plan-and-execute workflow
--
-- A plan is a goal-shaped workflow generated by Atlas (or hand-built):
-- "Grow Acme Plumbing's local visibility in Austin TX" → a sequence
-- of research, brief generation, page building, publishing, and
-- review steps that the system executes against existing engines.
--
-- Two tables:
--   kotoiq_plans       — one row per plan (goal + status + lifecycle)
--   kotoiq_plan_steps  — each step references an /api/kotoiq action
--                        with dispatch params; status advances as the
--                        executor runs them.
-- ============================================================

CREATE TABLE IF NOT EXISTS kotoiq_plans (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  agency_id uuid,
  goal text NOT NULL,                       -- "Grow Acme's local visibility…"
  summary text,                             -- Plan-level rationale from Atlas
  status text NOT NULL DEFAULT 'draft',
    -- 'draft' | 'approved' | 'running' | 'paused' | 'completed' | 'failed' | 'archived'
  context jsonb DEFAULT '{}',               -- services, areas, business_model, etc.
  meta jsonb DEFAULT '{}',                  -- model, cost_usd, generated_at
  created_at timestamptz DEFAULT now(),
  approved_at timestamptz,
  completed_at timestamptz,
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_kotoiq_plans_client_status
  ON kotoiq_plans(client_id, status);
CREATE INDEX IF NOT EXISTS idx_kotoiq_plans_agency_status
  ON kotoiq_plans(agency_id, status, created_at DESC);

CREATE TABLE IF NOT EXISTS kotoiq_plan_steps (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  plan_id uuid NOT NULL REFERENCES kotoiq_plans(id) ON DELETE CASCADE,
  sequence integer NOT NULL,                -- 1..N execution order
  kind text NOT NULL,
    -- 'research' | 'strategy' | 'brief' | 'page' | 'publish' | 'audit' |
    -- 'analyze' | 'approval' | 'manual'
  label text NOT NULL,                      -- "Generate strategy for Austin TX"
  description text,                         -- 1-2 sentence rationale
  status text NOT NULL DEFAULT 'pending',
    -- 'pending' | 'ready' | 'running' | 'completed' | 'failed' |
    -- 'skipped' | 'blocked' | 'manual_required'
  action text,                              -- /api/kotoiq action key, e.g. 'recommend_local_strategy'
  params jsonb DEFAULT '{}',                -- dispatch payload
  depends_on jsonb DEFAULT '[]',            -- array of plan_step ids that must complete first
  artifact_ref text,                        -- e.g. brief_id, suggestion_id, publish_id, strategy_run_id
  artifact_kind text,                       -- 'brief' | 'suggestion' | 'publish' | 'strategy' | 'analysis'
  result jsonb,                             -- step output summary
  error text,                               -- failure message when status='failed'
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_kotoiq_plan_steps_plan_seq
  ON kotoiq_plan_steps(plan_id, sequence);
CREATE INDEX IF NOT EXISTS idx_kotoiq_plan_steps_plan_status
  ON kotoiq_plan_steps(plan_id, status);

ALTER TABLE kotoiq_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE kotoiq_plan_steps ENABLE ROW LEVEL SECURITY;
