-- Visitor Profiles: persistent identity across sessions via browser fingerprint
-- Each unique visitor gets a profile that aggregates across all their sessions

create table if not exists koto_visitor_profiles (
  id uuid primary key default gen_random_uuid(),
  agency_id uuid not null,
  fingerprint text not null,                      -- canvas+webgl+screen hash

  -- Identity
  label text,                                     -- user-assigned label or auto-generated
  identified_company text,
  identified_domain text,
  identified_email text,
  identified_phone text,

  -- Geo (best known from IP lookups across sessions)
  city text,
  state text,
  country text,
  timezone text,
  language text,

  -- Device & Browser (from fingerprint data)
  device_type text,                               -- desktop, mobile, tablet
  browser text,
  browser_version text,
  os text,
  os_version text,
  screen_resolution text,                         -- e.g. "1920x1080"
  color_depth int,
  hardware_concurrency int,
  touch_support boolean default false,
  gpu_renderer text,                              -- WebGL renderer string
  connection_type text,                           -- 4g, wifi, etc.
  platform text,                                  -- navigator.platform

  -- Behavioral aggregates
  total_sessions int default 0,
  total_pageviews int default 0,
  total_time_seconds int default 0,
  total_form_submits int default 0,
  total_cta_clicks int default 0,
  pages_visited jsonb default '[]'::jsonb,        -- unique URLs across all sessions
  top_pages jsonb default '[]'::jsonb,            -- most viewed pages [{url, title, views}]
  referral_sources jsonb default '[]'::jsonb,     -- all referrers seen
  utm_history jsonb default '[]'::jsonb,          -- all UTM combos seen
  visit_times jsonb default '[]'::jsonb,          -- hour-of-day distribution
  visit_days jsonb default '[]'::jsonb,           -- day-of-week distribution
  avg_session_duration int default 0,
  max_intent_score int default 0,
  latest_intent_score int default 0,
  intent_signals jsonb default '[]'::jsonb,

  -- AI Persona (generated by Claude Haiku)
  ai_persona jsonb,                               -- { summary, segments, interests, buying_stage, ... }
  ai_persona_generated_at timestamptz,

  -- Lifecycle
  first_seen_at timestamptz default now(),
  last_seen_at timestamptz default now(),
  is_lead boolean default false,
  lead_created_at timestamptz,
  tags text[] default '{}',

  created_at timestamptz default now(),
  updated_at timestamptz default now(),

  unique(agency_id, fingerprint)
);

create index if not exists idx_visitor_profiles_agency on koto_visitor_profiles(agency_id);
create index if not exists idx_visitor_profiles_fingerprint on koto_visitor_profiles(agency_id, fingerprint);
create index if not exists idx_visitor_profiles_last_seen on koto_visitor_profiles(last_seen_at desc);
create index if not exists idx_visitor_profiles_intent on koto_visitor_profiles(max_intent_score desc);

-- Add fingerprint column to sessions so we can link them
alter table koto_visitor_sessions add column if not exists fingerprint text;
alter table koto_visitor_sessions add column if not exists visitor_profile_id uuid references koto_visitor_profiles(id);

-- Add fingerprint data columns to sessions
alter table koto_visitor_sessions add column if not exists screen_resolution text;
alter table koto_visitor_sessions add column if not exists color_depth int;
alter table koto_visitor_sessions add column if not exists hardware_concurrency int;
alter table koto_visitor_sessions add column if not exists touch_support boolean;
alter table koto_visitor_sessions add column if not exists gpu_renderer text;
alter table koto_visitor_sessions add column if not exists connection_type text;
alter table koto_visitor_sessions add column if not exists os text;
alter table koto_visitor_sessions add column if not exists os_version text;
alter table koto_visitor_sessions add column if not exists browser_version text;
alter table koto_visitor_sessions add column if not exists timezone text;
alter table koto_visitor_sessions add column if not exists language text;
alter table koto_visitor_sessions add column if not exists platform text;
alter table koto_visitor_sessions add column if not exists canvas_hash text;
alter table koto_visitor_sessions add column if not exists webgl_hash text;
alter table koto_visitor_sessions add column if not exists font_count int;
alter table koto_visitor_sessions add column if not exists current_page_title text;

create index if not exists idx_sessions_fingerprint on koto_visitor_sessions(fingerprint);
create index if not exists idx_sessions_profile on koto_visitor_sessions(visitor_profile_id);
